# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hexatiles < Formula
  desc "Parquet → H3 polygons → PMTiles in one command"
  homepage "https://github.com/samfargo/HexaTiles"
  version "0.2.0"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/samfargo/HexaTiles/releases/download/v0.2.0/hexatiles_0.2.0_darwin_arm64.tar.gz"
    sha256 "3373ef2abc795e30d1295ca866d05c7683e72cb968987c848aa0f68e4fc3987d"

    def install
      bin.install "hexatiles"
    end
  end

  test do
    system "#{bin}/hexatiles", "--help"
  end
end
