# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hexatiles < Formula
  desc "Parquet → H3 polygons → PMTiles in one command"
  homepage "https://github.com/samfargo/HexaTiles"
  version "0.1.4"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/samfargo/HexaTiles/releases/download/v0.1.4/hexatiles_0.1.4_darwin_amd64.tar.gz"
    sha256 "d7d3b5151f5254fde9d5856b73e003488ce8bedf68dc946ab6e1084ee5009847"

    def install
      bin.install "hexatiles"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/samfargo/HexaTiles/releases/download/v0.1.4/hexatiles_0.1.4_darwin_arm64.tar.gz"
    sha256 "4ee27fe4dd1ba81df77508421d1abb33cfb1babb1e87e1b743abb5bd0c80af27"

    def install
      bin.install "hexatiles"
    end
  end

  test do
    system "#{bin}/hexatiles", "--help"
  end
end
